import { AppItem, Category, IconName } from './types';

export const CATEGORIES: Category[] = ['全部', '教會', '職場', '工具', '創意', '數據', '遊戲', '其他'];

export const ICONS: IconName[] = ['Chat', 'Image', 'Music', 'Video', 'Brain', 'Zap', 'Church', 'Briefcase', 'BarChart', 'Heart'];

export const INITIAL_APPS: AppItem[] = [];

export const APP_TEMPLATES: Partial<AppItem>[] = [
  {
    name: '聖經導師 AI',
    description: '深入探討聖經真理的屬靈導師，提供解經與生活應用建議。',
    category: '教會',
    icon: 'Church',
    aspectRatio: '4:3',
  },
  {
    name: '職場智慧助手',
    description: '協助處理職場溝通、決策與團隊管理的 AI 助手。',
    category: '職場',
    icon: 'Briefcase',
    aspectRatio: '16:9',
  },
  {
    name: '數據分析專家',
    description: '視覺化分析業務數據，提供精準的營運洞察。',
    category: '數據',
    icon: 'BarChart',
    aspectRatio: '16:9',
  },
  {
    name: '創意寫作夥伴',
    description: '激發創意靈感，協助撰寫文案、故事與企劃。',
    category: '創意',
    icon: 'Brain',
    aspectRatio: '16:9',
  },
  {
    name: '遊戲化學習工具',
    description: '透過互動遊戲提升學習動機與知識留存。',
    category: '遊戲',
    icon: 'Zap',
    aspectRatio: '1:1',
  }
];

export const TRANSLATIONS = {
  zh: {
    title: '耶西-[AI Studio Apps]-的家',
    subtitle: '歡迎來到我的個人應用程式門戶',
    adminMode: '管理員模式',
    addApp: '新增應用程式',
    quickAdd: '快速新增範本',
    smartFetch: '智慧導入 (貼上網址)',
    smartSearch: '搜尋我的應用程式',
    fetching: '正在讀取應用程式資訊...',
    searching: '正在搜尋您的應用程式...',
    fetchSuccess: '成功讀取資訊！',
    fetchError: '讀取失敗，請檢查網址或手動輸入。',
    urlWarning: '偵測到 AI Studio 編輯網址。請使用「Share」功能產生的 Shared App URL (*.run.app) 以確保能正常嵌入預覽。',
    openExternal: '在新分頁開啟應用程式',
    iframeBlocked: '預覽被封鎖或無法載入？',
    editApp: '編輯',
    deleteApp: '刪除',
    cloneApp: '複製',
    save: '儲存',
    cancel: '取消',
    name: '名稱',
    description: '說明',
    link: '連結',
    category: '分類',
    icon: '圖示',
    aspectRatio: '顯示比例',
    confirmDelete: '確定要刪除這個應用程式嗎？',
    adminPasswordPrompt: '請輸入管理員密碼',
    password: '密碼',
    submit: '送出',
    incorrectPassword: '密碼錯誤，請重試。',
    categories: {
      '全部': '全部',
      '教會': '教會',
      '職場': '職場',
      '工具': '工具',
      '創意': '創意',
      '數據': '數據',
      '遊戲': '遊戲',
      '其他': '其他',
    },
    icons: {
      'Chat': '對話',
      'Image': '圖片',
      'Music': '音樂',
      'Video': '影片',
      'Brain': '智慧',
      'Zap': '效能',
      'Church': '教會',
      'Briefcase': '職場',
      'BarChart': '數據',
      'Heart': '喜愛',
    }
  },
  en: {
    title: "Jesse's [AI Studio Apps] Home",
    subtitle: 'Welcome to my personal application portal',
    adminMode: 'Admin Mode',
    addApp: 'Add App',
    quickAdd: 'Quick Templates',
    smartFetch: 'Smart Import (Paste URL)',
    smartSearch: 'Search My Apps',
    fetching: 'Fetching app info...',
    searching: 'Searching for your apps...',
    fetchSuccess: 'Info fetched successfully!',
    fetchError: 'Fetch failed. Please check the URL or enter manually.',
    urlWarning: 'AI Studio Editor URL detected. Please use the Shared App URL (*.run.app) from the "Share" menu to allow embedding.',
    openExternal: 'Open App in New Tab',
    iframeBlocked: 'Preview blocked or failed to load?',
    editApp: 'Edit',
    deleteApp: 'Delete',
    cloneApp: 'Clone',
    save: 'Save',
    cancel: 'Cancel',
    name: 'Name',
    description: 'Description',
    link: 'Link',
    category: 'Category',
    icon: 'Icon',
    aspectRatio: 'Aspect Ratio',
    confirmDelete: 'Are you sure you want to delete this app?',
    adminPasswordPrompt: 'Enter Admin Password',
    password: 'Password',
    submit: 'Submit',
    incorrectPassword: 'Incorrect password, please try again.',
    categories: {
      '全部': 'All',
      '教會': 'Church',
      '職場': 'Workplace',
      '工具': 'Tools',
      '創意': 'Creative',
      '數據': 'Data',
      '遊戲': 'Games',
      '其他': 'Other',
    },
    icons: {
      'Chat': 'Chat',
      'Image': 'Image',
      'Music': 'Music',
      'Video': 'Video',
      'Brain': 'Brain',
      'Zap': 'Zap',
      'Church': 'Church',
      'Briefcase': 'Briefcase',
      'BarChart': 'Data',
      'Heart': 'Heart',
    }
  }
};
